### ISSUE TITLE
Error: Cannot find module 'babel/polyfill'

### ISSUE THREAD

**Issue by flekschas** [kpdecker/six-speed#41]
I am trying to run the test on my local machine (Mac OS X 10.10.5) using Node (v5.6.0).

**My steps:**
1. `git clone https://github.com/kpdecker/six-speed && cd six-speed`
2. `npm install`
3. `npm run test:node`

**Complete output:**

```
running promises ["babel-loose","babel-runtime","babel","es5","es6","traceur","typescript"]
  running promises babel-loose 0
  running promises babel-runtime 0
  complete promises babel-runtime 0 729.2047824818535
  running promises babel 0
  complete promises babel-loose 0 724.8266986951824
  running promises es5 0
module.js:341
    throw err;
    ^

Error: Cannot find module 'babel/polyfill'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Fritz/Code/six-speed/lib/node-test.js:8:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
  complete promises es5 0 711.3579227901166
  running promises es6 0
  complete promises es6 0 774.780082238862
  running promises traceur 0
  complete promises traceur 0 763.2621554041476
  running promises typescript 0
  complete promises typescript 0 759.8577087074866
```

It seem to still run fine but I am wondering if it has any impact on the tests.

**Comment by kpdecker** [comment]
Not sure the impact on the tests, but I think I've fixed this an am re-running the test suite. Thanks for the report!
